// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, ExportInternshipReportData, ExportInternshipReportErrors, ExportInternshipReportResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, GetInternshipRunData, GetInternshipRunErrors, GetInternshipRunResponses, GetLatestInternshipReportData, GetLatestInternshipReportErrors, GetLatestInternshipReportResponses, GetUserData, GetUserErrors, GetUserResponses, HealthCheckData, HealthCheckErrors, HealthCheckResponses, ListInternshipRunArticlesData, ListInternshipRunArticlesErrors, ListInternshipRunArticlesResponses, ListInternshipRunsData, ListInternshipRunsErrors, ListInternshipRunsResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, RegisterData, RegisterErrors, RegisterResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Liveness check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>): RequestResult<HealthCheckResponses, HealthCheckErrors, ThrowOnError> => (options?.client ?? client).get<HealthCheckResponses, HealthCheckErrors, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Create an account
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Log in and get a bearer token
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get the logged-in user
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * Log out (revoke the current token)
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/logout',
    ...options
});

/**
 * Change your password
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>): RequestResult<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError> => (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete your own account
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> => (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}',
    ...options
});

/**
 * Read your own user
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>): RequestResult<GetUserResponses, GetUserErrors, ThrowOnError> => (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}',
    ...options
});

/**
 * Update your own username or name
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> => (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * The latest internship tracker report
 */
export const getLatestInternshipReport = <ThrowOnError extends boolean = false>(options?: Options<GetLatestInternshipReportData, ThrowOnError>): RequestResult<GetLatestInternshipReportResponses, GetLatestInternshipReportErrors, ThrowOnError> => (options?.client ?? client).get<GetLatestInternshipReportResponses, GetLatestInternshipReportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/internships/latest',
    ...options
});

/**
 * Run history
 */
export const listInternshipRuns = <ThrowOnError extends boolean = false>(options?: Options<ListInternshipRunsData, ThrowOnError>): RequestResult<ListInternshipRunsResponses, ListInternshipRunsErrors, ThrowOnError> => (options?.client ?? client).get<ListInternshipRunsResponses, ListInternshipRunsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/internships/runs',
    ...options
});

/**
 * A run's report
 */
export const getInternshipRun = <ThrowOnError extends boolean = false>(options: Options<GetInternshipRunData, ThrowOnError>): RequestResult<GetInternshipRunResponses, GetInternshipRunErrors, ThrowOnError> => (options.client ?? client).get<GetInternshipRunResponses, GetInternshipRunErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/internships/runs/{id}',
    ...options
});

/**
 * The documents a run tried to read
 */
export const listInternshipRunArticles = <ThrowOnError extends boolean = false>(options: Options<ListInternshipRunArticlesData, ThrowOnError>): RequestResult<ListInternshipRunArticlesResponses, ListInternshipRunArticlesErrors, ThrowOnError> => (options.client ?? client).get<ListInternshipRunArticlesResponses, ListInternshipRunArticlesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/internships/runs/{id}/articles',
    ...options
});

/**
 * Download a run's Markdown report
 */
export const exportInternshipReport = <ThrowOnError extends boolean = false>(options: Options<ExportInternshipReportData, ThrowOnError>): RequestResult<ExportInternshipReportResponses, ExportInternshipReportErrors, ThrowOnError> => (options.client ?? client).get<ExportInternshipReportResponses, ExportInternshipReportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/internships/runs/{id}/report.md',
    ...options
});
