// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ChangePasswordBody
 */
export type ChangePasswordBody = {
    currentPassword: string;
    newPassword: string;
};

/**
 * ChangePasswordResponse
 */
export type ChangePasswordResponse = {
    /**
     * The new bearer token. Every previous token is revoked.
     */
    token: string;
};

/**
 * Error
 */
export type Error = {
    error: ErrorBody;
};

/**
 * ErrorBody
 */
export type ErrorBody = {
    code: ErrorCode;
    message: string;
    details?: Array<ValidationIssue>;
};

/**
 * ErrorCode
 */
export type ErrorCode = 'VALIDATION_ERROR' | 'UNAUTHORIZED' | 'INVALID_CREDENTIALS' | 'NOT_FOUND' | 'METHOD_NOT_ALLOWED' | 'USERNAME_TAKEN' | 'INVALID_PASSWORD' | 'INTERNAL';

/**
 * Health
 */
export type Health = {
    status: 'ok';
};

/**
 * InternshipOffer
 *
 * One opportunity as the run reported it. Fields the posting doesn't state are
 * `unknown` (or null for pay, deadline and the work-authorization quote).
 */
export type InternshipOffer = {
    /**
     * Stable across runs.
     */
    opportunityId: number;
    /**
     * `new` since the last run, still in the `top_k`, `dropped` from the last run's top K or closed this run, or also `open`.
     */
    section: 'new' | 'top_k' | 'dropped' | 'open';
    rank: number | null;
    topK: boolean;
    /**
     * The rank in the last run, if it had one.
     */
    previousRank: number | null;
    /**
     * Why a `dropped` offer left the report's top K. Null in other sections.
     */
    dropReason: 'closed' | 'outranked' | null;
    company: string;
    title: string;
    roleType: string;
    term: string;
    locations: Array<string>;
    remote: string;
    url: string;
    compensation: string | null;
    deadline: string | null;
    /**
     * The posting's own words, quoted. Never a judgment.
     */
    workAuthorizationQuote: string | null;
    summary: string | null;
    status: 'open' | 'unknown' | 'closed';
    statusEvidence: string | null;
    /**
     * Checked open in this run.
     */
    verified: boolean;
    firstSeenAt: string;
};

/**
 * InternshipReport
 */
export type InternshipReport = {
    /**
     * Null until the first run is published.
     */
    run: TrackerRun | null;
    offers: Array<InternshipOffer>;
};

/**
 * LoginBody
 */
export type LoginBody = {
    /**
     * Case-insensitive.
     */
    username: string;
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Send as `Authorization: Bearer <token>`.
     */
    token: string;
    user: User;
};

/**
 * RegisterBody
 */
export type RegisterBody = {
    /**
     * 3-30 letters, digits, `_` or `.`. Case-insensitive; stored lowercased.
     */
    username: string;
    password: string;
    firstName?: string;
    lastName?: string;
};

/**
 * TrackerArticle
 *
 * One document a run tried to read. Title and URL came from the web: show them as
 * text, and link the URL only when it is http(s).
 */
export type TrackerArticle = {
    /**
     * `scout`, `collect`, `curate`, or `agent`.
     */
    stage: string;
    kind: 'page' | 'board' | 'posting';
    url: string;
    /**
     * Empty when the document was not fetched.
     */
    title: string;
    /**
     * `skipped`: already seen. `rejected`: refused by a fetch guardrail.
     */
    status: 'fetched' | 'skipped' | 'rejected' | 'failed';
    /**
     * Why it was rejected or failed.
     */
    reason: string | null;
    fetchedAt: string;
};

/**
 * TrackerArticleList
 */
export type TrackerArticleList = {
    /**
     * In fetch order.
     */
    articles: Array<TrackerArticle>;
};

/**
 * TrackerRun
 *
 * One daily internship tracker run.
 */
export type TrackerRun = {
    id: string;
    topic: string;
    status: 'complete' | 'partial' | 'failed';
    stopReason: string | null;
    startedAt: string;
    endedAt: string | null;
    /**
     * The run's full Markdown report.
     */
    reportMarkdown: string;
};

/**
 * TrackerRunList
 */
export type TrackerRunList = {
    /**
     * Newest first.
     */
    runs: Array<TrackerRunSummary>;
};

/**
 * TrackerRunSummary
 *
 * One published run and what changed in it, for the run history.
 */
export type TrackerRunSummary = {
    id: string;
    topic: string;
    status: 'complete' | 'partial' | 'failed';
    stopReason: string | null;
    startedAt: string;
    endedAt: string | null;
    /**
     * How many offers the run reported in each section, e.g. `new`.
     */
    sections: {
        [key: string]: number;
    };
    /**
     * How many documents the run tried to read, by status, e.g. `fetched`.
     */
    articles: {
        [key: string]: number;
    };
};

/**
 * UpdateUserBody
 */
export type UpdateUserBody = {
    /**
     * 3-30 letters, digits, `_` or `.`. Case-insensitive; stored lowercased.
     */
    username?: string;
    firstName?: string;
    lastName?: string;
};

/**
 * User
 *
 * A user. Never includes credentials.
 */
export type User = {
    id: string;
    username: string;
    firstName: string;
    lastName: string;
    createdAt: string;
    updatedAt: string;
};

/**
 * ValidationIssue
 */
export type ValidationIssue = {
    path: Array<string | number>;
    code: string;
    message: string;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthCheckErrors = {
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type HealthCheckError = HealthCheckErrors[keyof HealthCheckErrors];

export type HealthCheckResponses = {
    /**
     * The server is up.
     */
    200: Health;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type RegisterData = {
    body: RegisterBody;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterErrors = {
    /**
     * The body is not valid JSON or fails validation.
     */
    400: Error;
    /**
     * The username is already taken.
     */
    409: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * The created user. No token; log in next.
     */
    201: User;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginBody;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * The body is not valid JSON or fails validation.
     */
    400: Error;
    /**
     * Unknown username or wrong password (indistinguishable).
     */
    401: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * A bearer token and the user.
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetCurrentUserErrors = {
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * The logged-in user.
     */
    200: User;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * The token is revoked. Your other sessions stay valid.
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ChangePasswordData = {
    body: ChangePasswordBody;
    path?: never;
    query?: never;
    url: '/api/auth/change-password';
};

export type ChangePasswordErrors = {
    /**
     * The body is not valid JSON or fails validation.
     */
    400: Error;
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * The current password is wrong.
     */
    403: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Every session is revoked, including this one. Use the returned token from now on.
     */
    200: ChangePasswordResponse;
};

export type ChangePasswordResponse2 = ChangePasswordResponses[keyof ChangePasswordResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * Id
         *
         * The user's id (must be your own).
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * The id is not your own. Same response whether it belongs to someone else, doesn't exist or isn't a UUID.
     */
    404: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Deleted. All of your sessions are revoked.
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * Id
         *
         * The user's id (must be your own).
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserErrors = {
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * The id is not your own. Same response whether it belongs to someone else, doesn't exist or isn't a UUID.
     */
    404: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * The user.
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UpdateUserBody;
    path: {
        /**
         * Id
         *
         * The user's id (must be your own).
         */
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * The body is not valid JSON or fails validation.
     */
    400: Error;
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * The id is not your own. Same response whether it belongs to someone else, doesn't exist or isn't a UUID.
     */
    404: Error;
    /**
     * The username is already taken by another user.
     */
    409: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * The updated user.
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type GetLatestInternshipReportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internships/latest';
};

export type GetLatestInternshipReportErrors = {
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type GetLatestInternshipReportError = GetLatestInternshipReportErrors[keyof GetLatestInternshipReportErrors];

export type GetLatestInternshipReportResponses = {
    /**
     * The latest published run and its offers, best rank first.
     */
    200: InternshipReport;
};

export type GetLatestInternshipReportResponse = GetLatestInternshipReportResponses[keyof GetLatestInternshipReportResponses];

export type ListInternshipRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         *
         * At most this many runs.
         */
        limit?: number;
    };
    url: '/api/internships/runs';
};

export type ListInternshipRunsErrors = {
    /**
     * The body is not valid JSON or fails validation.
     */
    400: Error;
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type ListInternshipRunsError = ListInternshipRunsErrors[keyof ListInternshipRunsErrors];

export type ListInternshipRunsResponses = {
    /**
     * Published runs, newest first, with what changed in each.
     */
    200: TrackerRunList;
};

export type ListInternshipRunsResponse = ListInternshipRunsResponses[keyof ListInternshipRunsResponses];

export type GetInternshipRunData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/internships/runs/{id}';
};

export type GetInternshipRunErrors = {
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * No published run with this id.
     */
    404: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type GetInternshipRunError = GetInternshipRunErrors[keyof GetInternshipRunErrors];

export type GetInternshipRunResponses = {
    /**
     * The run and its offers, best rank first.
     */
    200: InternshipReport;
};

export type GetInternshipRunResponse = GetInternshipRunResponses[keyof GetInternshipRunResponses];

export type ListInternshipRunArticlesData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/internships/runs/{id}/articles';
};

export type ListInternshipRunArticlesErrors = {
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * No published run with this id.
     */
    404: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type ListInternshipRunArticlesError = ListInternshipRunArticlesErrors[keyof ListInternshipRunArticlesErrors];

export type ListInternshipRunArticlesResponses = {
    /**
     * Pages, job boards and postings, in fetch order, with their status.
     */
    200: TrackerArticleList;
};

export type ListInternshipRunArticlesResponse = ListInternshipRunArticlesResponses[keyof ListInternshipRunArticlesResponses];

export type ExportInternshipReportData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/internships/runs/{id}/report.md';
};

export type ExportInternshipReportErrors = {
    /**
     * Missing, malformed, unknown or expired token.
     */
    401: Error;
    /**
     * No published run with this id, or it has no report.
     */
    404: Error;
    /**
     * Unexpected server error.
     */
    500: Error;
};

export type ExportInternshipReportError = ExportInternshipReportErrors[keyof ExportInternshipReportErrors];

export type ExportInternshipReportResponses = {
    /**
     * The tracker's own report for the run, as published.
     */
    200: string;
};

export type ExportInternshipReportResponse = ExportInternshipReportResponses[keyof ExportInternshipReportResponses];
